### ISSUE TITLE
as.data.frame

### ISSUE THREAD

**Issue by willpearse** [willpearse/pez#53]
...not exported (...at least on my computer), I think!

**Comment by stevencarlislewalker** [comment]
I may certainly be missing something, but I think this is the expected behaviour of the `@export` tag.  For example, this works,

```{r}
library(pez)
data(laja)
data <- comparative.comm(invert.tree, river.sites, invert.traits, river.env)
as.data.frame(data)
```

but not this

```{r}
as.data.frame.comparative.comm(data)
```

as is expected.  If someone wants to look at `as.data.frame.comparative.comm` they need,

```{r}
pez:::as.data.frame.comparative.comm
```

or

```{r}
getAnywhere(as.data.frame.comparative.comm)
```

Although I can't find any "Hadley-approved" 8) discussion on the topic, this link seems reasonable enough:

http://stackoverflow.com/questions/18512528/how-to-export-s3-method-so-it-is-available-in-namespace?answertab=active#tab-top

As always, I certainly could be missing something.

**Comment by willpearse** [comment]
...Thanks Steve, you're completely right. I think I've just had one of
those "aaaaaaaag!" moments when sat at a laptop with someone.

Thank you!!!

Will

**Comment by stevencarlislewalker** [comment]
Been there 8)

**Comment by willpearse** [comment]
:D
